name: Backend EC2 Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Latest Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install
       

      - name: Deploy to EC2
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --exclude=node_modules --delete
          path: ./server/
          remote_path: ~/app
          remote_host: ${{secrets.EC2_HOST}}
          remote_port: 22
          remote_user: ${{secrets.EC2_USERNAME}}
          remote_key: ${{secrets.EC2_SSH_PRIVATE_KEY}}
